[workspace]
resolver = "2"
members = [
  "discriminator",
  "discriminator-derive",
  "discriminator-syn",
  "generic-token",
  "generic-token-tests",
  "pod",
  "program-error",
  "program-error-derive",
  "tlv-account-resolution",
  "type-length-value",
  "type-length-value-derive",
  "type-length-value-derive-test",
]

[workspace.metadata.cli]
solana = "2.3.4"

# Specify Rust toolchains for rustfmt, clippy, and build.
# Any unprovided toolchains default to stable.
[workspace.metadata.toolchains]
nightly = "nightly-2025-02-16"

[workspace.metadata.spellcheck]
config = "scripts/spellcheck.toml"

[workspace.metadata.release]
pre-release-commit-message = "Publish {{crate_name}} v{{version}}"
tag-message = "Publish {{crate_name}} v{{version}}"
consolidate-commits = false

[patch.crates-io]
solana-account-info = { git = "https://github.com/jupnet/jupnet-sdk", branch = "main" }
solana-address = { git = "https://github.com/jupnet/jupnet-sdk", branch = "main" }
solana-atomic-u64 = { git = "https://github.com/jupnet/jupnet-sdk", branch = "main" }
solana-borsh = { git = "https://github.com/jupnet/jupnet-sdk", branch = "main" }
solana-hash = { git = "https://github.com/jupnet/jupnet-sdk", branch = "main" }
solana-instruction = { git = "https://github.com/jupnet/jupnet-sdk", branch = "main" }
solana-instruction-error = { git = "https://github.com/jupnet/jupnet-sdk", branch = "main" }
solana-msg = { git = "https://github.com/jupnet/jupnet-sdk", branch = "main" }
solana-program-error = { git = "https://github.com/jupnet/jupnet-sdk", branch = "main" }
solana-program-memory = { git = "https://github.com/jupnet/jupnet-sdk", branch = "main" }
solana-program-option = { git = "https://github.com/jupnet/jupnet-sdk", branch = "main" }
solana-pubkey = { git = "https://github.com/jupnet/jupnet-sdk", branch = "main" }
solana-sanitize = { git = "https://github.com/jupnet/jupnet-sdk", branch = "main" }
solana-sdk-ids = { git = "https://github.com/jupnet/jupnet-sdk", branch = "main" }
solana-sha256-hasher = { git = "https://github.com/jupnet/jupnet-sdk", branch = "main" }
solana-zk-sdk = { git = "https://github.com/jupnet/zk-elgamal-proof", branch = "jupnet" }
